/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CommPortDialog.java
 *
 * Created on 24.5.2012, 19:08:41
 */

package cz.vutbr.fit.gja.proj;

import java.util.Enumeration;
import java.util.Vector;
import gnu.io.*;
import org.jdesktop.application.Action;

/**
 *
 * @author Martin Falticko
 */
public class CommPortDialog extends javax.swing.JDialog {


  /** Seznam portu **/
  Vector<String> portNames;
  GJAProjectView mainParent;

  /** Creates new form CommPortDialog */
  public CommPortDialog(GJAProjectView mainWindow,java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();


    mainParent=mainWindow;
    Enumeration<CommPortIdentifier> portList;
    Vector<String> portVect = new Vector<String>();
    portList = CommPortIdentifier.getPortIdentifiers();

    CommPortIdentifier portId;
    while (portList.hasMoreElements()) {
      portId = (CommPortIdentifier) portList.nextElement();
      if (portId.getPortType() == CommPortIdentifier.PORT_SERIAL) {
        portVect.add(portId.getName());
      }
    }
    portNames = portVect;

    for (String s : portNames) {
      selectBox.addItem(s);
    }

  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selectBox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cz.vutbr.fit.gja.proj.GJAProjectApp.class).getContext().getResourceMap(CommPortDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        selectBox.setName("selectBox"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cz.vutbr.fit.gja.proj.GJAProjectApp.class).getContext().getActionMap(CommPortDialog.class, this);
        jButton2.setAction(actionMap.get("Cancel")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton1.setAction(actionMap.get("Apply")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(selectBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  @Action
  public void Cancel()
  {
    this.setVisible(false);
  }

  @Action
  public void Apply()
  {
    int index=selectBox.getSelectedIndex();
    if(index>=0)
    {
      mainParent.startLoadingActual(portNames.get(index));
    }
    this.setVisible(false);
  }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox selectBox;
    // End of variables declaration//GEN-END:variables

}
