/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfigForm.java
 *
 * Created on 2.12.2010, 0:59:11
 */

package cz.vutbr.fit.gja.proj;

import java.io.FileNotFoundException;
import org.jdesktop.application.Action;
import cz.vutbr.fit.gja.proj.utils.*;
import java.awt.*;
import java.io.FileInputStream;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import org.jdesktop.application.Application;


/**
 * Konfiguracni formular pro aplikaci
 *
 * @author Martin Falticko
 * 
 */
public class ConfigForm extends javax.swing.JDialog {

    /**
     * Konfigurace aplikace
     */
    private Config config;

    /**
     * Zpusob ukonceni formulare - false = storno, true = ok
     */
    public boolean modalResult;

    /**
     * Konstruktor
     *
     * @param parent Rodicovske okono
     */
    public ConfigForm(java.awt.Frame parent) {
        super(parent);

        modalResult = false;

        initComponents();

        this.setModalityType(Dialog.ModalityType.DOCUMENT_MODAL);



        try
        {
            config = Application.getInstance(GJAProjectApp.class).getConfiguration();
            this.gpsXField.setText(String.valueOf(config.getMapCenter().lng));
            this.gpsYField.setText(String.valueOf(config.getMapCenter().lat));
            this.zoomField.setSelectedIndex(config.getMapZoom() - 1);
        }
        catch(Exception e)
        {
            //JOptionPane.showMessageDialog(this,e.getMessage(),"Chyba",JOptionPane.ERROR_MESSAGE,new ImageIcon(getClass().getResource("/resources/rosnicka.gif")) );
        }
    }

    /**
     * Kopiruje hodnoty z formularovych poli do objektu Config
     *
     * @return true pokud prosla validace hodnot a lze ulozit
     */
    private boolean storeValues() {

      try {
        config.setMapCenter(new GPSPoint(Double.parseDouble(this.gpsYField.getText()), Double.parseDouble(this.gpsXField.getText())));
      }
      catch(Exception e) {
          JOptionPane.showMessageDialog(this, "Chybný formát čísla pro GPS souřadnice.", "Chyba",JOptionPane.ERROR_MESSAGE );
          return false;
      }


     

      config.setMapZoom((short)(this.zoomField.getSelectedIndex() + 1));



      return true;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpsXField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gpsYField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        zoomField = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cz.vutbr.fit.gja.proj.GJAProjectApp.class).getContext().getResourceMap(ConfigForm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        gpsXField.setName("gpsXField"); // NOI18N
        gpsXField.setPreferredSize(new java.awt.Dimension(200, 20));

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        gpsYField.setName("gpsYField"); // NOI18N
        gpsYField.setPreferredSize(new java.awt.Dimension(200, 20));

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cz.vutbr.fit.gja.proj.GJAProjectApp.class).getContext().getActionMap(ConfigForm.class, this);
        btnCancel.setAction(actionMap.get("btnCancelClicked")); // NOI18N
        btnCancel.setDefaultCapable(false);
        btnCancel.setLabel(resourceMap.getString("btnCancel.label")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N

        btnOK.setAction(actionMap.get("btnOKClicked")); // NOI18N
        btnOK.setText(resourceMap.getString("btnOK.text")); // NOI18N
        btnOK.setName("btnOK"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        zoomField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        zoomField.setSelectedIndex(10);
        zoomField.setName("zoomField"); // NOI18N

        jButton1.setAction(actionMap.get("deleteMapChache")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(gpsYField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(gpsXField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(zoomField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(154, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpsXField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpsYField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zoomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ulozeni udaju do souboru. Spusteno po kliknuti na tlacitko OK.
     */
    @Action
    public void btnOKClicked()
    {
        try
        {
            GPSPoint p=new GPSPoint(config.getMapCenter());
            if (! this.storeValues())
              return;
            GPSPoint p2=config.getMapCenter();
            if(p.lat!=p2.lat || p.lng != p2.lng)
            {
                BingMapsStat.clearImageCache();
            }
            
            
            
            config.saveConfig(Config.defaultConfigFile);
            
            modalResult = true;

            this.dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage(),"Chyba",JOptionPane.ERROR_MESSAGE );
        }
    }

    /**
     * Stornovani kliknutim na tlacitko Storno
     */
    @Action
    public void btnCancelClicked()
    {
        modalResult = false;
        this.dispose();
    }

  @Action
  public void deleteMapChache() {
    BingMapsStat.clearImageCache();
  }

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JTextField gpsXField;
    private javax.swing.JTextField gpsYField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox zoomField;
    // End of variables declaration//GEN-END:variables



}

