/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DisplayStatsPanel.java
 *
 * Created on 12.12.2010, 23:28:12
 */

package cz.vutbr.fit.gja.proj;

import cz.vutbr.fit.gja.proj.utils.GPSPoint;
import cz.vutbr.fit.gja.proj.utils.Globals;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.application.Application;

/**
 * Panel s vyhledavanim druhu, podle pozice kliknuti na mape
 *
 * @author Pavel Dziadzio
 */
public class DisplayStatsPanel extends javax.swing.JPanel {

  /**
   * Souradnice kliknuti na mapu
   */
    private GPSPoint point;

    /**
     * Hodnota radiusu vyhledavani v kilometrech
     */
    private double radius;



    /**
     * Nastavene datum, ke kteremu jsou pozadovany data
     */
    private Calendar selDate;

    /**
     * Konstruktor
     */
    public DisplayStatsPanel() {
        initComponents();

        /*try
        {
        spec = new Species(Application.getInstance(PDBProjectApp.class).getConnection());

        
        }catch(Exception e)
        {
            
        }*/

        selDate = Calendar.getInstance();
    }


    /**
     * Nastavi souradnice kliknuti na mapu
     *
     * @param p GPS souradnice kliknuti
     * @param radius Hodnota radiusu vyhledavani v kilometrech
     */
    public void setGPS(GPSPoint p, double radius) {
        this.point=p;
        this.radius = radius;
        gpsLabel.setText(String.format("%.5f %.5f", p.lat, p.lng));

        eDate.setValue(this.selDate.getTime());

        loadData();

    }

    /**
     * Nacteni dat z databaze s zobrazeni v gridu
     */
    private void loadData() {
      /*DefaultTableModel model = (DefaultTableModel)tResultTable.getModel();

      model.setRowCount(0);

      spec = new Species(Application.getInstance(PDBProjectApp.class).getConnection());

      spec.searchByPoint(this.point, this.selDate, this.radius);

      while (spec.next()) {
        BufferedImage img = null;

        if (spec.getPhotos().loadPrimaryImage()) {
          try {
            BufferedImage origimg = ImageIO.read(spec.getPhotos().imageProxy.getDataInStream());


            double ration;
            if (origimg.getWidth() > origimg.getHeight()) {
              ration = origimg.getWidth()/(double)48;
            }
            else {
              ration = origimg.getHeight()/(double)48;
            }

            int w = (int) (origimg.getWidth() / ration);
            int h = (int) (origimg.getHeight() / ration);

            img = new BufferedImage(w, h, BufferedImage.TYPE_USHORT_555_RGB);

            img.getGraphics().drawImage(origimg, 0, 0, w, h, null);

          } catch (SQLException ex) {
            Logger.getLogger(SearchForm.class.getName()).log(Level.SEVERE, null, ex);
          }
          catch (IOException ex) {
            Logger.getLogger(SearchForm.class.getName()).log(Level.SEVERE, null, ex);
          }
        }

        model.addRow(new Object[] {img, spec.name, spec.lname});
      }*/
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        gpsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eDate = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tResultTable = new javax.swing.JTable();
        bSetDate = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 400));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cz.vutbr.fit.gja.proj.GJAProjectApp.class).getContext().getResourceMap(DisplayStatsPanel.class);
        gpsLabel.setText(resourceMap.getString("gpsLabel.text")); // NOI18N
        gpsLabel.setMaximumSize(new java.awt.Dimension(300, 20));
        gpsLabel.setMinimumSize(new java.awt.Dimension(300, 20));
        gpsLabel.setName("gpsLabel"); // NOI18N
        gpsLabel.setPreferredSize(new java.awt.Dimension(300, 20));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        eDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        eDate.setEnabled(false);
        eDate.setName("eDate"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Foto", "Název", "Latinský název"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tResultTable.setName("tResultTable"); // NOI18N
        tResultTable.setRowHeight(50);
        tResultTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tResultTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tResultTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tResultTable);
        tResultTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tResultTable.getColumnModel().getColumn(0).setMinWidth(50);
        tResultTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        tResultTable.getColumnModel().getColumn(0).setMaxWidth(50);
        tResultTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tResultTable.columnModel.title0")); // NOI18N
        tResultTable.getColumnModel().getColumn(0).setCellRenderer(new ImageColumnRenderer());
        tResultTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tResultTable.columnModel.title1")); // NOI18N
        tResultTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tResultTable.columnModel.title2")); // NOI18N

        bSetDate.setIcon(resourceMap.getIcon("bSetDate.icon")); // NOI18N
        bSetDate.setText(resourceMap.getString("bSetDate.text")); // NOI18N
        bSetDate.setEnabled(false);
        bSetDate.setName("bSetDate"); // NOI18N
        bSetDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetDateActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText(resourceMap.getString("jRadioButton1.text")); // NOI18N
        jRadioButton1.setName("jRadioButton1"); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText(resourceMap.getString("jRadioButton2.text")); // NOI18N
        jRadioButton2.setName("jRadioButton2"); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(eDate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSetDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(gpsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gpsLabel, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addGap(11, 11, 11)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(eDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSetDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Doubleclick na gridu - zobrazeni druhu na mape
     */
    private void tResultTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tResultTableMouseClicked
     /* if (evt.getClickCount() == 2) {
        int srow = tResultTable.getSelectedRow() + 1;

        if ((srow > 0) && spec.rowByIndex(srow)) {
          spec.getAreas().selectAtTime();
          spec.getAreas().next();
          Globals.species=spec;
          Globals.fireSpeciesChangedEvent("", InfoEvent.CODE_INFO);
        }
      }*/
    }//GEN-LAST:event_tResultTableMouseClicked

    /**
     * Obnoveni dat po zmene datumu
     */
    private void bSetDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetDateActionPerformed
      Date dt = (Date)eDate.getValue();
      this.selDate.setTime(dt);

      loadData();
    }//GEN-LAST:event_bSetDateActionPerformed

    /**
     * Vyber - aktualni data
     */
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
      eDate.setEnabled(false);
      bSetDate.setEnabled(false);
      this.selDate = Calendar.getInstance();

      loadData();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * Vyber - ke dni
     */
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
      eDate.setEnabled(true);
      bSetDate.setEnabled(true);
      eDate.setValue(this.selDate.getTime());
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSetDate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField eDate;
    private javax.swing.JLabel gpsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tResultTable;
    // End of variables declaration//GEN-END:variables

}
